# Generated by Django 2.2.3 on 2019-07-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('field_name', models.CharField(blank=True, max_length=255, null=True)),
                ('precision', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=244)),
                ('slug_name', models.CharField(blank=True, max_length=244, null=True)),
                ('layer_type', models.CharField(choices=[('XYZ', 'XYZ'), ('WMS', 'WMS'), ('ArcRest', 'ArcRest'), ('radio', 'radio'), ('checkbox', 'checkbox'), ('Vector', 'Vector'), ('placeholder', 'placeholder')], max_length=50)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('shareable_url', models.BooleanField(default=True)),
                ('proxy_url', models.BooleanField(default=False, help_text='proxy layer url through marine planner')),
                ('arcgis_layers', models.CharField(blank=True, max_length=255, null=True)),
                ('wms_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('is_sublayer', models.BooleanField(default=False)),
                ('legend', models.CharField(blank=True, max_length=255, null=True)),
                ('legend_title', models.CharField(blank=True, max_length=255, null=True)),
                ('legend_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('utfurl', models.CharField(blank=True, max_length=255, null=True)),
                ('utfjsonp', models.BooleanField(default=False)),
                ('summarize_to_grid', models.BooleanField(default=False)),
                ('filterable', models.BooleanField(default=False)),
                ('geoportal_id', models.CharField(blank=True, help_text='GeoPortal UUID', max_length=255, null=True)),
                ('proj', models.CharField(blank=True, help_text='will be EPSG:3857, if unspecified', max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('data_overview', models.TextField(blank=True, null=True)),
                ('data_source', models.CharField(blank=True, max_length=255, null=True)),
                ('data_notes', models.TextField(blank=True, null=True)),
                ('bookmark', models.CharField(blank=True, max_length=755, null=True)),
                ('map_tiles', models.CharField(blank=True, max_length=255, null=True)),
                ('kml', models.CharField(blank=True, max_length=255, null=True)),
                ('data_download', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute_title', models.CharField(blank=True, max_length=255, null=True)),
                ('compress_display', models.BooleanField(default=False)),
                ('attribute_event', models.CharField(choices=[('click', 'click'), ('mouseover', 'mouseover')], default='click', max_length=35)),
                ('lookup_field', models.CharField(blank=True, max_length=255, null=True)),
                ('vector_color', models.CharField(blank=True, max_length=7, null=True)),
                ('vector_fill', models.FloatField(blank=True, null=True)),
                ('vector_graphic', models.CharField(blank=True, max_length=255, null=True)),
                ('opacity', models.FloatField(blank=True, default=0.5, null=True)),
                ('attribute_fields', models.ManyToManyField(blank=True, to='data_manager.AttributeInfo')),
            ],
        ),
        migrations.CreateModel(
            name='LookupInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('dashstyle', models.CharField(choices=[('dot', 'dot'), ('dash', 'dash'), ('dashdot', 'dashdot'), ('longdash', 'longdash'), ('longdashdot', 'longdashdot'), ('solid', 'solid')], default='solid', max_length=11)),
                ('fill', models.BooleanField(default=False)),
                ('graphic', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('header_image', models.CharField(blank=True, max_length=255, null=True)),
                ('header_attrib', models.CharField(blank=True, max_length=255, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, max_length=255, null=True)),
                ('factsheet_thumb', models.CharField(blank=True, max_length=255, null=True)),
                ('factsheet_link', models.CharField(blank=True, max_length=255, null=True)),
                ('feature_image', models.CharField(blank=True, max_length=255, null=True)),
                ('feature_excerpt', models.TextField(blank=True, null=True)),
                ('feature_link', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TOCTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('layers', models.ManyToManyField(blank=True, to='data_manager.Layer')),
            ],
        ),
        migrations.CreateModel(
            name='TOC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('themes', models.ManyToManyField(blank=True, to='data_manager.TOCTheme')),
            ],
        ),
        migrations.AddField(
            model_name='layer',
            name='lookup_table',
            field=models.ManyToManyField(blank=True, to='data_manager.LookupInfo'),
        ),
        migrations.AddField(
            model_name='layer',
            name='sublayers',
            field=models.ManyToManyField(blank=True, related_name='_layer_sublayers_+', to='data_manager.Layer'),
        ),
        migrations.AddField(
            model_name='layer',
            name='themes',
            field=models.ManyToManyField(blank=True, to='data_manager.Theme'),
        ),
        migrations.CreateModel(
            name='DataNeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('archived', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('expected_date', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('themes', models.ManyToManyField(blank=True, to='data_manager.Theme')),
            ],
        ),
    ]
