# Generated by Django 2.2.3 on 2019-07-03 11:58

import caching.base
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('slug', models.CharField(max_length=125)),
                ('description', models.TextField(blank=True, null=True)),
                ('parents', models.ManyToManyField(blank=True, related_name='_term_parents_+', to='ontology.Term')),
            ],
            bases=(caching.base.CachingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RDFConcept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=255)),
                ('preflabel', models.CharField(max_length=125)),
                ('definition', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(default='', max_length=125)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ontology.RDFConcept')),
            ],
            options={
                'abstract': False,
            },
            bases=(caching.base.CachingMixin, models.Model),
        ),
    ]
